spring.application.name=Climalert

# --- WeatherAPI ---
weatherapi.base-url=https://api.weatherapi.com/v1
weatherapi.key=${WEATHERAPI_KEY}
weatherapi.location=Buenos Aires

# --- Resend (correo) ---
resend.api-key=${RESEND_API_KEY}


